FROM ruby:3.2.3

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

WORKDIR /rails

COPY Gemfile Gemfile.lock ./

# Install all gems including development
RUN bundle install

COPY . .

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]
